import type { Project, Publication } from "./types"

export const projectsData: Project[] = [
  {
    id: 1,
    title: "Machine Learning Risk Assessment",
    description: "A financial risk assessment system using advanced ML algorithms",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Python", "TensorFlow", "Pandas", "AWS"],
    demoUrl: "#",
    githubUrl: "#",
    featured: true,
  },
  {
    id: 2,
    title: "Predictive Analytics Dashboard",
    description: "Interactive dashboard for visualizing predictive models and financial data",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["React", "D3.js", "Node.js", "MongoDB"],
    demoUrl: "#",
    githubUrl: "#",
    featured: true,
  },
  {
    id: 3,
    title: "Algorithmic Trading System",
    description: "Automated trading system using statistical models and machine learning",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Python", "NumPy", "Pandas", "SQL"],
    demoUrl: "#",
    githubUrl: "#",
    featured: true,
  },
  {
    id: 4,
    title: "Financial Data ETL Pipeline",
    description: "Scalable ETL pipeline for processing financial market data",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Apache Spark", "Scala", "AWS", "Airflow"],
    demoUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    id: 5,
    title: "Natural Language Processing for Financial News",
    description: "NLP system for analyzing sentiment in financial news articles",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Python", "NLTK", "SpaCy", "PyTorch"],
    demoUrl: "#",
    githubUrl: "#",
    featured: false,
  },
  {
    id: 6,
    title: "Blockchain-based Smart Contracts",
    description: "Implementation of financial smart contracts on blockchain",
    image: "/placeholder.svg?height=300&width=500",
    technologies: ["Solidity", "Ethereum", "Web3.js", "JavaScript"],
    demoUrl: "#",
    githubUrl: "#",
    featured: false,
  },
]

export const publicationsData: Publication[] = [
  {
    id: 1,
    title: "Analysis of the Goldbach Conjecture and Primo-Raduis",
    journal: "IJPSAT Journal",
    year: 2022,
    abstract: "A comprehensive analysis of the Goldbach Conjecture with novel approaches to prime number theory.",
    url: "https://ijpsat.org/index.php/ijpsat/article/view/795",
  },
  {
    id: 2,
    title: "Advanced Number Theory Applications in Cryptography",
    journal: "Google Scholar",
    year: 2021,
    abstract: "Exploring applications of number theory in modern cryptographic systems and security protocols.",
    url: "https://scholar.google.com/citations?view_op=view_citation&hl=en&user=CP3DJqYAAAAJ&citation_for_view=CP3DJqYAAAAJ:d1gkVwhDpl0C",
  },
  {
    id: 3,
    title: "Machine Learning Approaches to Financial Risk Assessment",
    journal: "Journal of Financial Mathematics",
    year: 2023,
    abstract: "Novel machine learning techniques for assessing and predicting financial risks in volatile markets.",
    url: "#",
  },
  {
    id: 4,
    title: "Statistical Models for Stress Testing in Banking",
    journal: "International Journal of Banking",
    year: 2020,
    abstract: "Development and validation of statistical models for stress testing in the banking sector.",
    url: "#",
  },
]

